set(FVCV_DOWNLOAD_VERSION ccf29dc00cde21d78140b1b9698d6bf075b3ab76)
set(FVCV_HASH_SUM "a3097481cedf3d7cdbdd3a20551da54e1627fe16fbe9aa18b9c7a1c70b50274e")
set(FVCV_DOWNLOAD_URL "https://raw.githubusercontent.com/scikit-build/cmake-FindVcvars/${FVCV_DOWNLOAD_VERSION}/FindVcvars.cmake")
set(FVCV_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/FindVcvars.cmake")
# Expand relative path. This is important if the provided path contains a tilde (~)
get_filename_component(FVCV_DOWNLOAD_LOCATION ${FVCV_DOWNLOAD_LOCATION} ABSOLUTE)
if(NOT EXISTS ${FVCV_DOWNLOAD_LOCATION})
  file(DOWNLOAD ${FVCV_DOWNLOAD_URL} ${FVCV_DOWNLOAD_LOCATION} EXPECTED_HASH SHA256=${FVCV_HASH_SUM})
else()
  file(SHA256 ${FVCV_DOWNLOAD_LOCATION} current_hash)
  if(NOT ${current_hash} STREQUAL ${FVCV_HASH_SUM})
    file(DOWNLOAD ${FVCV_DOWNLOAD_URL} ${FVCV_DOWNLOAD_LOCATION} EXPECTED_HASH SHA256=${FVCV_HASH_SUM})
  endif()
endif()
list(INSERT CMAKE_MODULE_PATH 0 ${CMAKE_BINARY_DIR}/cmake)
